name = "VehicleRadios";
author = "MattyboyH2003";
logo = "logo.paa";
logoOver = "logo.paa";
tooltip = "Vehicle Radios";
picture = "picture.paa";
actionName = "GitHub";
action = "https://github.com/MattyboyH2003";
overview = "You can listen to Taylor Swift in arma!";
